version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
      - ~/.ssh:/home/docker/.ssh
      - ~/.gitconfig:/home/docker/.gitconfig
    tty: true
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_SQLITE3: 1
      PHP_EXTENSION_PDO_SQLITE: 1
      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: "client_port=9003 client_host=localhost"
